### ISSUE TITLE
Principles: Update principles to reflect both engineering and architecture disciplines

### ISSUE THREAD

**Issue by GrahamR-HO** [UKHomeOffice/engineering-and-architecture#6]
Update principles to reflect both engineering and architecture disciplines - clarifying each principle, to ensure a clear rationale and description - including alignment to GDS principles.

**Comment by timgent** [comment]
NB: Gabby not yet on assignee list but should work on this too

**Comment by gabbym54** [comment]
@timgent @shabe @Abdul2 @GrahamR-HO - Guys, are we basing this on my straw man from a week or so ago?  If so, do we want to publish that somewhere so we can work on it?

**Comment by shabe** [comment]
Hi @gabbym54 do you want me to put the straw-man into a googledoc so that we can update it together?

**Comment by gabbym54** [comment]
Hi @shabe yes please, great idea

**Comment by shabe** [comment]
De-duplication of Eng & Arch principles:

https://docs.google.com/spreadsheets/d/1dSiJQDzBLDIJcR2GKRWJ8_LSUkUYeAcgVUrGMJwrucQ/edit#gid=0

**Comment by shabe** [comment]
For context, shared by the GDS Architecture team in this morning's meeting:

Document is publicly open:

- https://docs.google.com/presentation/d/1jj8mndjx0ZYXo0ZS9V9AZRlh0-enuZVYF1L44Myj80Q/edit#slide=id.p68

I quite like that most of our principles derive to their 9 key points.

**Comment by shabe** [comment]
First pass at the de-duplicated principles from 42 down to 15, as follows:

- D1	Principle D1: Information is treated as an asset
- D2	Principle D2: Information is appropriately protected secured and accessed
- E1	Principle E1. One Home Office
- EA2	Minimise vendor lock-in
- EA4	Build services as twelve factor apps
- EA8	Continuous delivery by default
- EA10	Build for modern web browsers, avoid mobile apps
- EA11	Make things accessible
- EA12	Follow [our standards] (standards.md) for languages, frameworks, techniques and tools
- EA13	Cloud native
- EA16	Build for measurability and operational readiness
- P1	Principle P1: Common platforms and reusable components
- P3	Principle P3: Open Standards, Open Data, Open Source
- SC1	Principle Sc1: Security by design
- U1	Principle U1: Services are designed around the needs of the user

**Comment by danielepolencic** [comment]
moved to: https://github.com/UKHomeOffice/engineering-and-architecture-board/issues/241
